User.create(first_name: 'Jorge', last_name: "Calvo", phone: "987654321", email:"jorge.calvo@tektonlabs.com", password: "asdasdasd")
User.create(first_name: 'Eduardo', last_name: "Arenas", phone: "987654321", email:"eduardo.arenas@tektonlabs.com", password: "asdasdasd")
User.create(first_name: 'Kevin', last_name: "Martin", phone: "987654321", email:"kevin.martin@tektonlabs.com", password: "asdasdasd")
User.create(first_name: 'Giancarlo', last_name: "Guzman", phone: "987654321", email:"giancarlo.guzman@tektonlabs.com", password: "asdasdasd")
User.create(first_name: 'Gustavo', last_name: "Galarreta", phone: "987654321", email:"gustavo.galarreta@tektonlabs.com", password: "asdasdasd")
